### ISSUE TITLE
"Undefined function or variable 'psiAnalysis'. "

### ISSUE THREAD

**Issue by Gwynase** [GMashayekhi/ManifoldEM_Matlab#1]
Wonderful work! This package will helps us a lot! 

I have an issue when I was using this package analyzing the Demo-data, Ryr1, in the tutorial.  
In first several steps I got good results, the same with tutorial, and the program work smoothly.  
At the step of NLSA, Matlab reported errors and I attached the command window below.  

![1601002325530](https://user-images.githubusercontent.com/49516140/94221200-2e0d9d00-ff1d-11ea-8b3d-efecd699ba34.jpg)

There's a function, psiAnalysis, matlab could not find, even after I double checked the work path of matlab. 

I'll be very appreciate if you can share your thought!

**Comment by GMashayekhi** [comment]
Hi,

Thanks for your interest and feedback. I am happy to hear that it would be helpful for you. 
Sorry, for some reason it was not uploaded. I did upload it. Let me know if you had any issues.

Best,
Ghoncheh

**Comment by Gwynase** [comment]
Hi @GMashayekhi 

Thank you very much, problem solved! 

Sorry to disturb you again.  There's a new problem when I go through the tutorial. In the step of "propagate the CC", according to the tutorial there's a slcPsimuns.mat file in the Demo Data folder. In the One Drive link shared in tutorial, I can't find it. 

And another thing is a question I want to ask, if I may: Is this ManifoldEM package contains the  program of generating complex energy landscape? 

By the way, if you think contact by email is more convenient, here's my email address: chuxf@@shanghaitech.edu.cn  (remove one @ please )

Thanks again! Looking forward to your return. 

Best 
Xiaofeng

**Comment by GMashayekhi** [comment]
Hi,

The user should provide that file. Please refer to the tutorial, section "Propagate the conformational coordinate (CC) among prDs". I will upload the one for the provided demo data in the folder as an example.
Regarding your second question, in this software the 1D energy landscape is provided. Depending on your system, if there are more than one conformational coordinates, you need to go through the steps for both conformational coordinates. Then, I can help you with next steps.

Best,
Ghoncheh

**Comment by Gwynase** [comment]
Hi,

@GMashayekhi Thank you very much for your explanation. I have a small question:
 I have finished analyzing the Demo-data and I already got 50 .mrcs files their .star files. If I want to check the 1D energy landscape, which scripts should I use? 

Looking forward to your return, thanks again!
Hope you have a good weekend.

Best
Xiaofeng

**Comment by GMashayekhi** [comment]
Hi,

Great! In the Dat folder, a mat file with the name of indsinbinRC1.mat would be saved. You need to load it to your workspace and run the following commands:

load('indsinbinRC1.mat', 'indsinbin')
l=cellfun(@length,indsinbin);
figure;plot(l/sum(l),'o-');

This gives you the occupancy of each state. You can convert it to Energy using Boltzmann equation.

Best,
Ghoncheh

**Comment by Gwynase** [comment]
Hi @GMashayekhi !

Thank you very much! I don't have any experience in using matlab and now I can use the software, thanks to you. 
And I still have 2 questions, if I may: 

1. During the step of making 2D movies of the demo-data, sometime this error occurs:
![Screenshot from 2020-10-13 13-52-01](https://user-images.githubusercontent.com/49516140/95942037-c6a88600-0e14-11eb-8f1d-16a56cdeeaad.png)
Sometime it works smoothly but sometime it stops and reporting this error. 
So,  I want to know if there's something I can do to fix it.
2.  I noticed that GUI can only import one star file and one mrcs file at a time. But RELION generate a mrcs file for each EM image. Now I have over 5k mrcs files to upload T^T. Is there any method or toolbox for combining .mrcs files?

Thanks again!
Looking forward to your return.

Best,
Xiaofeng

**Comment by GMashayekhi** [comment]
Hi,

Glad to hear!

1. Before answering, let me know, what input parameters did you use and which PDs have this error?

2. As explained in the tutorial, this software is for conformational analysis after the step in which each single particle projection (what we call snapshot) has been assigned an orientation. In other words, you should use ManifoldEM after doing a consensus refinement without any conformational heterogeneity classification. Basically you can use any software for the preprocessing until you get orientations for each single particle projection. We have provided the Relion compatible format as an example. But other softwares also can be used and one needs to modify the necessary codes to convert from that format to ManifoldEM acceptable format.
Short answer to your question: Do all preprocessing steps in Relion (Movie correction, particle extraction, CTF, junk removals, 3D refinement). Then you would have one star file (orientations) and one mrcs file(single particle projections), you would need to feed them to the ManifoldEM software. 

Best,
Ghoncheh

**Comment by Gwynase** [comment]
Hi, @GMashayekhi 

Thank you  very much! 

1. I tried again, this time Making 2D movies works well. Maybe I made a mistake in parameter setting. 

2. Thanks for the explanation! Sorry I didn't make myself clear. 
I want to analysis a dataset which has been refined by RELION 3D AutoRefine and. ManifoldEM requires particles (.mrcs files) and their .star file. But in RELION, the .mrcs files of the particles after 3D refinement with particles's 3D orientations, are separately distributed.  In my case, after 3D refinement, there are 5000 .mrcs files containing 200k particles. And I'm a rookie in Matlab, so I wonder if there's a way to upload all the .mrcs file in ManifoldEM or I need to combine all the .mrcs files into one file? Is there any toolkit for combining mrcs files?

Thanks again!

Best, 
Xiaofeng

**Comment by GMashayekhi** [comment]
Hi,

Sorry for misunderstanding. You should be able to do that by Relion using "relion_preprocess" to merge several stacks into one .mrcs file. Please set --norm true and --recenter true .  

If you could not do that, we can do it in Matlab. For that, I need to write some lines of codes. Please try it with Relion first.

Best,
Ghoncheh

**Comment by Gwynase** [comment]
Got it! Thanks!

Best,
Xiaofeng
