### ISSUE TITLE
error message in NSLA

### ISSUE THREAD

**Issue by Gwynase** [GMashayekhi/ManifoldEM_Matlab#2]
Hi, 

Thanks for the contribution! 
Some errors were reported during the NSLA while the demo data works pretty well. The errors occur The error message is attached below: 

![image](https://user-images.githubusercontent.com/49516140/96856482-88ecd280-1490-11eb-8507-422ed27b3cd0.png)

This is a test dataset of ribosome: 200,000 particles, boxsize =440, pixel size=1.06. And star file contains their 3D angles. Here I attached the results before NLSA. I hope this can help you analysis the error message. 

First is the star file head and import parameter:
![image](https://user-images.githubusercontent.com/49516140/96857140-39f36d00-1491-11eb-9fbe-5531964b286e.png)
![10 21](https://user-images.githubusercontent.com/49516140/96856950-09133800-1491-11eb-9efb-22db04ec4190.png)

Second is the Tessellation result:
GreatCircles:
![1021](https://user-images.githubusercontent.com/49516140/96857876-209ef080-1492-11eb-9ab5-3150fe7dcffa.png)

S2:
![123](https://user-images.githubusercontent.com/49516140/96859105-b0916a00-1493-11eb-8211-106c6e3ae0ce.png)

If I choose Great Circles to execute Distance Calculation, there will be a error:
![sss](https://user-images.githubusercontent.com/49516140/96858713-395bd600-1493-11eb-81f0-6452a7d9518d.png)

So, I choose S2 to continue. And at the step of NSLA, the errors I mentioned at the beginning were reported. Any idea of fixing this?

Thanks for your time! 

Best,
Xiaofeng

**Comment by GMashayekhi** [comment]
Hi,

Please be aware that, when you receive such an error, it is just for one single Projection direction (PD). The star file would not help to debug. You should see what is wrong in that specific PD. 
My guess: due to not enough number of snapshots, the NLSA did not converge. If it is happening in so many PDs of yours we can play with some parameters to fix it. But if it is just a few PDs, we can ignore them.

PS: If you want me to help with debugging, you should share the Dist file related to that specific PD with me.

Best,
Ghoncheh

**Comment by Gwynase** [comment]
> Hi,
> 
> Please be aware that, when you receive such an error, it is just for one single Projection direction (PD). The star file would not help to debug. You should see what is wrong in that specific PD.
> My guess: due to not enough number of snapshots, the NLSA did not converge. If it is happening in so many PDs of yours we can play with some parameters to fix it. But if it is just a few PDs, we can ignore them.
> 
> PS: If you want me to help with debugging, you should share the Dist file related to that specific PD with me.
> 
> Best,
> Ghoncheh

Thank you very much! 
The error occured not in a certain prD. I tried two times it happens in two different prDs. Here's one:
![image](https://user-images.githubusercontent.com/49516140/96951432-0f4ff580-151f-11eb-8221-026237452788.png)
And I uploaded IMGs_prD238.mat: https://drive.google.com/file/d/1nAusipS0YX9ylLnnPtPnDFk1B05pBJIm/view?usp=sharing
There are 175 particles in this prD, I guess? 
And I checked all the Dit file, there're many prDs that contains less than 150 particles... 
Should I increase the parameter 'Aperture Index' to decrease the prD number?  
  
Thanks again! 

Best,
Xiaofeng

**Comment by GMashayekhi** [comment]
Yes, there are 175 particles in this PD.  It does not mean that, this would happen in all PDs with snapshot numbers less than 175. That depends on the PD. What would I do, is that, I would ignore these 2 PDs for now. I would look at 2D movies, to see if I can detect the conformational motions. If I could detect it in most of the PDs, it shows the parameters are ok and we can proceed with them. If not we can play with the parameters.

BTW, I could not access the file and I requested for access.

Best,
Ghoncheh

**Comment by Gwynase** [comment]
I see, thanks. And how should I ignore the prDs with small number of particles? Should I delete the mat file in folder 'Dist'? 
And I noticed there are 3 scripts in folder 'ExtraCodes': 'RemoveClasters', 'readNSLAres' and 'readEMres'. Could you please give me some examples of how to use these scripts?

Thanks again!

Best,
Xiaofeng

**Comment by GMashayekhi** [comment]
If you are ruining on clusters you just need to ignore those jobs. But I think you are running on a single machine. Then you should skip the indices related to those PDs in each single for loop (NLSA, 2D movie,..).

Best,
Ghoncheh

**Comment by Gwynase** [comment]
Hi, @GMashayekhi 

Thanks for the suggestions! It's very useful. NSLA is now finished.
Apologize for the disturbing but I met another error in Making 2D movies T^T. 
Here's the situation: I finished the NLSA by cluster computation. And when I click the 'Make 2D Movie' button, an error came up. 
Here I attached the error and the GUI at the step of 'making 2D movies'
![Capture](https://user-images.githubusercontent.com/49516140/97588200-38004f80-1a37-11eb-97ec-68b12f6c1ed3.PNG)
![1Capture](https://user-images.githubusercontent.com/49516140/97588207-39ca1300-1a37-11eb-98ec-ee2b794c3f10.PNG)

Thanks!

Best,
Xiaofeng

**Comment by GMashayekhi** [comment]
Hi,

This error shows that in make2Dmovies, it was not possible to fetch the NLSA results from cluster. Are you sure that, NLSA was fine?! You need to check the NLSA files in the NLSA folder in the cluster.

Note: make2Dmovie is being run on the host machine whereas NLSA has been done on the cluster. So by fetching, the NLSA files are being read from the cluster. Another way would have been to copy the NLSA files from cluster to the host machine and run the make2Dmovie.

Best,
Ghoncheh

**Comment by Gwynase** [comment]
Hi, 

I see, thanks! I downloaded the NLSA and made 2D movies at a local workstation with the parameter like thiis:
![image](https://user-images.githubusercontent.com/49516140/97709368-2c735e00-1af5-11eb-9312-feb7b54b5d22.png)
 And an error appeared: 
![image](https://user-images.githubusercontent.com/49516140/97711027-82490580-1af7-11eb-9bbe-495c15577606.png)
This error appeared not in a certain index of prD or certain psi. May I ask why this error occurs? I can continue the program 'making 2D movies' from where it stopped by changing the prD index in the code, but it stopped again after processing several prD files with the same error. 

Thanks for your patience, I think I've send you too many emails.

Best,
Xiaofeng
