### ISSUE TITLE
Questions about "slcPsinums.mat"

### ISSUE THREAD

**Issue by Gwynase** [GMashayekhi/ManifoldEM_Matlab#3]
Hi, @GMashayekhi 

Thanks for the previous explanation. I have a question about editing file "slcPsinums.mat" which is needed in "Propagate the CC" step. 

Based on my understanding, the file slcPsinums.mat contains two column, and the line numbers represent the prD numbers which means the first line represents prD1 and the second line represents prD2. The first column is the psi number I want to choose in this certain prD. Am I right?

And I can't fully understand the second column, 'sense'. Can I consider 'sense' as the direction of protein movement? If I observed two same movements in 2D movies but are towards to two opposite directions, should the sense number be 1 and -1, respectively? 

Thanks again!

Best,
Xiaofeng

**Comment by GMashayekhi** [comment]
Hi,

Yes! You are right.

Best,
Ghoncheh

**Comment by GMashayekhi** [comment]
Hi

How is it going with your dataset and the software? Let me know if you had
any questions.

Thanks,
Ghoncheh

**Comment by Gwynase** [comment]
Hi! @GMashayekhi 

Thank you for asking me! Now I can use this program smoothly. 
As for questions I do have one: 
I have finished analyzing 1-D free-energy landscape of one protein molecule in two different conditions. And I want to compare the differences of free-energy landscape between these two conditions. The swing of this molecule in two different conditions are same but are different in amplitudes. Based on my understanding, the swing range are different in these two conditions making the x coordinates of 1D landscape different. I wonder is there any way to normalize x axis in order to make two 1-D landscape curves comparable? 
What I trying to solve this question is to combine these 2 conditions and finish the free-landscape calculation in one step. I combined mrcs and star files from these 2 different conditions and added a column of labels in star file denoting where the particle came from, for example here, "1" and "2".  During the calculation in matlab, I wrote an extra file, matrix of label, which is identical with the matrix of Euler Angle ,"q". All the transformations that executed to matrix q were accurately executed to matrix of label.  So, I wrote a 4 x 2n, n is number of particles, matrix of label, identical to euler angle matrix, q, in the program. At last, writing an extra column of label in dat files and star files, and followed by classification according to the label and counting the particles of each condition in each frame can make two landscapes comparable. 
I don't know if I make myself clear. I wander what do think of this idea, if I may ? 

Much appreciated!

Best,
Xiaofeng

**Comment by GMashayekhi** [comment]
Hi,

If you embed the datasets together, the conformational coordinates would be
the same. We did the same for RyR in our Nature Communication 2020 paper
where we had two datasets; with and without ligand, bearing in mind that
nothing else has changed in data acquisition setup.

To do this with the ManioldEM code, you need to combine the two .star files
at the beginning. You know that first n are from dataset 1 and last n are
from dataset two. Then you need to proceed till the end of software and
there is no need for any changes. But after embedding, I would look at the
manifolds (EM folder) to see if any clustering happens ( I can help you
with that if you want).

At the final stage, where you want to plot the 1D energy landscapes, you
need to separate these two datasets.  Where you "load('indsinbinRC1.mat',
'indsinbin')". Now based on the indices being smaller than n or larger than
n in each of the 50 bins, you can separate them and have two
separate energylandscape for each dataset.

I hope it was clear. Let me know if you had any problems.

Best,
Ghoncheh

**Comment by Gwynase** [comment]
Hi! @GMashayekhi 

I see, thanks for the suggestion!

 I already finished picking 2D movies. And the movements in movies are continuous and smoothly, is it necessary to re-check the embedding data?  

And I also have a question: 
After analyzing several datasets, I found that in the results of 1D free-energy landscapes the particle number of first and last frame are abnormally larger. Here I put two results, the first one is RYR1 demo data and the second one is a dataset from myself. 
![image](https://user-images.githubusercontent.com/49516140/106725093-f12c8200-6643-11eb-8e53-187d5fcd5ec7.png)
![image](https://user-images.githubusercontent.com/49516140/106726104-fccc7880-6644-11eb-8273-0f2fd0f6d94c.png)
Y axis coordinate represents particle number. 
The particle numbers of the first and the last frame are abnormally high. 
These results make me feel that the x axises are too short and the particles that located outside the range of x coordinate stacked at frame 1 and 50. Is there any way to fix that or should I just omit the frame 1 and frame 50? 

Much appreciated! 

Best,
Xiaofeng

**Comment by GMashayekhi** [comment]
Hi,

Great! Is the motion you are seeing the same as when you were analyzing the
individual datasets? or is it different? Looking at the manifolds will show
you the distribution of points. Sometimes this gives us additional hint
about the data.

We have talked about what you are saying as the boundary problem in the
limitation section of ReadMe. Short answer, it is better to ignore them.

Best,
Gonche

**Comment by Gwynase** [comment]
Hi! @GMashayekhi 

I see, thanks!
I think the movements in movies are identical with individual datasets. 
No more questions for now, and I truly appreciate your timely help! 

Best,
Xiaofeng

**Comment by Gwynase** [comment]
Hi! @GMashayekhi 

Hope you have nice weekend, and sorry for bothering you again. I have finished analyzing two datasets by combining them together. And I have a question about the result. 
These two datasets are from a protein in two different conditions and the movements in these 2 datasets are exactly same . In first condition the protein molecules are flexible, we can't get an acceptable EM map due to the conformational heterogeneity. And in the second condition the protein molecules are relatively rigid, less conformational heterogeneity, and we can get an acceptable EM map from the second condition dataset. 
According to that, we think in condition one the particle occupancy distribution curve of different conformations is a flattened peak and in condition two the distribution curve is narrow and sharp. But in the result of free-energy landscape analysis, the particle distributions of these 2 conditions are almost same. So I want to ask, in the program, is this a right way to analyze the conformational heterogeneity distributions change? Is there any procedure in the program such as normalizing which will omit or cover the conformational distribution variability?  
Much appreciated!

Best,
Xiaofeng

**Comment by GMashayekhi** [comment]
Hi,

Let's, go through this once again to be sure we are on the same page:
- You combined these two datasets(rigid, more flexible) together, and fed
it as the input to ManifoldEM
- You ran all the ManifoldEM steps until the point to get the energy
landscape.
- At that last step, to have the energy landscape for each dataset, you
only count the snapshots belonging to that specific dataset in calculating
the occupancy.
- When you look at the distribution of snapshots in along the
conformational coordinate, they seem similar for both datasets, whereas one
should have had a limited range of motions.

Is that correct?

In principle, with this pipeline you should see this difference between the
distribution of the datasets in ManifoldEM. Now let's debug.

1. Are you sure that, you have done these steps correctly?
2. Could it be the case that, there is a second conformational coordinate,
in which one is more rigid and the other not?!
3. Here again, I go back to my old suggestion. To double check the results,
you need to scatter plot the manifolds of the PDs and color the points
based on the datasets. The manifold will have two colors. You can see if
one color is aggregated in some specific region of the manifold or not.
(Let me know if you need help with scatter plotting)

Best,
Ghoncheh

**Comment by Gwynase** [comment]
Hi! @GMashayekhi 

Yes! That pipeline is exactly what I'm trying to do. It looks like there's something wrong in it. Psi1 in embedding files are n x 50 forms, and I don't know how to check the EM or NLSA data by plotting them. Could you show me an example? 
Thanks for your time! 

Best,
Xiaofeng

**Comment by GMashayekhi** [comment]
Hi

In the EM_prD*.mat file, there is a variable called Psi1. The columns are the eigenvectors (by default you have 50 eigenvectors), the raws are representing the snapshots. You need to scatterplot the eigenvectors (either 3D or for different pairs), and color the points based on the datasets they are coming from. You should have a plot like what we have in Supplementary Fig.7b (Dashti, A., Mashayekhi, G., Shekhar, M. et al. Retrieving functional pathways of biomolecules from single-particle snapshots. Nat Commun 11, 4734 (2020).). In Supplementary Fig.7b, psi1 vs psi2 is plotted. And, you see most of the snapshots belonging to the two datasets are distributed in two different regions of the psi1, whereas in psi2 they are indistinguishable.

Best,
Ghoncheh

**Comment by Gwynase** [comment]
Hi! @GMashayekhi 

Thanks for your patients! I find your script "scriptRemoveCluster.m" in ExtraCodes folder is very useful.  And I also found the noted code that color the dots by "n" in CG as the picture I attached below. 

![image](https://user-images.githubusercontent.com/49516140/107929972-5756c480-6fb5-11eb-9b12-c735587820a4.png)

I have a question about coloring dots by "n". Actually I fed combined 3 different datasets to the program, 100,000 particles each, totally 300k snapshots. And I noticed that variable "q" storing processed Euler angle is 4 x 600k matrix, because of "q = [q, qc];" in "getStarFile.m". And I also found the maximum number in CG is about 600k, so I want to ask is the arrangement of CG same with "q"? If I want to select the first class particles, first 100K snapshots, is it right to set CG range of 1- 100k and 300k-400k? In short, how can I identify first 100,000 snapshots from 300,000 dataset in CG which is in range of 1-600,000?
And second question is when using scriptRemoveCluster.m how to move next prD after finishing selecting dots by polygon? 

Much appreciated! 

Best,
Xiaofeng

**Comment by Gwynase** [comment]
Hi! @GMashayekhi 

So sorry to bother you again and thanks for your time. 
There's a question I want to ask, if I may.  After I scatter-plotted the "psi1" in embedding files and found that some prDs contains only one color of data (This time I combined 2 datasets and colored them by particle number), but the movies generated by these kinds of prDs are good. Should I discard them? 

Thank you very much!

Best,
Xiaofeng
